import React from "react";

const Friends = () => {
  return (
    <div>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
        <h3>Ashirya & Sandeep </h3>
   </div>
  );
};

export default Friends;
